export const type = {
    ON_SUCCESS_GET_LIST_KATERING_BY_RATING: 'ON_SUCCESS_GET_LIST_KATERING_BY_RATING',
    ON_FAILURE_GET_LIST_KATERING_BY_RATING: 'ON_FAILURE_GET_LIST_KATERING_BY_RATING'
};

export default type